config/routes.rb
Organizer::Application.routes.draw do
  root 'welcome#index'

  resources :site_managers

  post '/site_managers/find_image' => 'site_managers#find_image'

  get '/search_images' => 'site_managers#search_images', as: :search_images

  post '/move_item' => 'site_managers#move_item', as: :move_item
end

app/models/site_manager.rb
class SiteManager < ActiveRecord::Base
  #late night this feels too minimalistic (should be checking the host as well https:// will validate)
  validates :url,:format => URI::regexp(%w(http https))
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/site_managers_controller.rb
class SiteManagersController < ApplicationController
  include SiteManagersHelper
  before_action :set_site_manager, only: [:show, :edit, :update, :destroy]


  def new
    @site_manager = SiteManager.new
  end

  def edit
    $site = parse_site(@site_manager.url)
  end

  def create
    @site_manager = SiteManager.new(site_manager_params)
    @site_manager.order = SiteManager.count(:all)

    respond_to do |format|
      if @site_manager.save
        format.html { redirect_to edit_site_manager_path(@site_manager), notice: 'Site manager was successfully created.' }
        format.js {}
        format.json { render action: 'show', status: :created, location: @site_manager }
      else
        format.html { render action: 'new' }
        format.json { render json: @site_manager.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @site_manager.update(site_manager_params)
        format.html { redirect_to root_path, notice: 'Site was successfully updated' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @site_manager.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @site_manager.destroy
    reset_order
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Site Successfully Removed' }
      format.json { head :no_content }
    end
  end

  def reset_order
    @sites = SiteManager.order("site_managers.order asc").find_all
    i = 0
    @sites.each do |f|
      f.order = i
      f.save
      i += 1
    end
  end

  def move_item
    set_site_manager
    order = @site_manager.order
    if params[:direction] == "left"
      replacement = SiteManager.find_by_order(order-1)
      @site_manager.order = order - 1
      replacement.order = order
    else #too general for move to front/back but will work for now
      replacement = SiteManager.find_by_order(order+1)
      @site_manager.order = order + 1
      replacement.order = order
    end
    @site_manager.save
    replacement.save

    respond_to do |format|
      format.js {render js: "location.reload();"}
    end
  end

  def search_images
    @images = return_images($site, 5)
    i = 1
    str = ''
    @images.each do |f|
      str << "<div class=\"image_selector\" data-img-num=\"#{i}\"><img src=\"#{f.to_s}\"></div>"
      i += 1
    end

    respond_to do |format|
      format.js { render js: "$('#images').html('#{str}');" }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_site_manager
      @site_manager = SiteManager.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def site_manager_params
      params.require(:site_manager).permit(:name, :url, :img, :order)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    def index
      @sites = SiteManager.order("site_managers.order asc").find_all
    end
end

app/helpers/site_managers_helper.rb
require 'google-search'

module SiteManagersHelper
  def return_images(str,num)
    images = []
    Google::Search::Image.new(:query => str, :image_size => :small).each do |image|
      images << image.uri if image.width < 200
      break if images.size == num
    end
    images
  end

  def parse_site(site_url)
    host = Addressable::URI.parse(site_url).host
    host = host.gsub("www.", "").gsub(/(\.[a-z]*)+/, "")
    host
  end

=begin
First Mechanize google crawler before I got smart and googled for the search api gem O_o
    get_request = 'http://images.google.com/images?q='
    get_request << str
    get_request << '&tbs=isz:ex,iszw:200,iszh:200'

    logger.debug "GET REQUEST: #{get_request}"

    agent = Mechanize.new #the money shot
    page = agent.get(get_request)
    images = []

    page.links.each do |link|
      begin
        clicked_page = link.click if link.uri.to_s.include? '/url?q'
      rescue Exception
        clicked_page = nil
      end


      if(clicked_page)
        clicked_page.images.each do |l|
          begin
            q = l.to_s
          rescue Exception
            next
          end
          if(q.include?(str))
            break if images.size>=num
            images << l if FastImage.size(l.url) == [200,200]
          end
        end
      end
    end

    images
  end
=end

=begin
Had a funny name so I gave it a shot and was severely disappointed with the image selection options
#ImageSuckr Too unreliable because of the random(results.size) zzz
    suckr = ImageSuckr::GoogleSuckr.new
    images = []

    while( images.size < num )
      url = suckr.get_image_url({"q" => str,   "imgsz" =>"icon"})
      #next if FastImage.size(url)[0]
      images << url
    end
    images
  end
=end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Organizer</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => false %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => false %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="container">
  <div id="content">
    <div id="header">WORKFLOW ORGANIZER</div>
    <div id="toolbar"><ul><li><%= link_to 'Home', root_path %></li><li><%= link_to 'Add Site to Homepage', new_site_manager_path %></li></ul></div>
    <div id="pages"><%= yield %></div>
    <div id="footer">v0.0 - Dan Bradbury</div>
  </div>
</div>
</body>
</html>

app/views/site_managers/_form.html.erb
<%= form_for(@site_manager) do |f| %>
  <% if @site_manager.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@site_manager.errors.count, "error") %> prohibited this site_manager from being saved:</h2>

      <ul>
      <% @site_manager.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :url %>
    <%= f.text_field :url %>
  </div>
  <% if @site_manager.img %>
    Current Image: <img src="<%= @site_manager.img %>">
  <% end %>
  <% if !@site_manager.new_record? %>
      <div class="field">
        <%= f.hidden_field :img %>
      </div>
  <% end %>
  <div class="actions">
    <%= f.submit "Save"%>
  </div>
<% end %>

app/views/site_managers/edit.html.erb
<h1>Select Image for Site</h1>

<%= link_to "Find Images", search_images_path, remote: true %>

<div id="images">
  <% if @images %>
      <% @i = 1 %>
      <% @images.each do |f| %>
          <div class="image_selector" data-img-num="<%= @i %>"><img src="<%= f.to_s %>"></div>
          <% @i += 1 %>
      <% end %>
  <% end %>
</div><br>

<%= render 'form' %>

app/views/site_managers/new.html.erb
<h1>Add Site to Homepage</h1>

<%= render 'form' %>

<%= link_to 'Back Home', site_managers_path %>

app/views/welcome/_site_list.html.erb
<% @count = 0 %>
<div class="site_list">
  <% @sites.each do |f| %>

      <div class="site" id="<%= @count %>">
        <div class="edit"><%= link_to('Move Left', move_item_path(:id => f, :direction => "left"), remote: true, method: :post) if @count != 0 %> <%= link_to('Move Right', move_item_path(:id => f, :direction => "right"), remote: true, method: :post) if @count != @sites.size-1 %> <%= link_to 'Modify', edit_site_manager_path(f) %> <%= link_to 'Destroy', f, method: :delete, data: { confirm: 'Are you sure?' } %></div>
        <a href="<%= f.url %>" target="_blank"><img src="<%= f.img %>" style="border:none; display:block;margin: 50px auto;"></a>
      </div>
      <% @count += 1 %>
  <% end %>
</div>

app/views/welcome/index.html.erb
<p id="notice"><%= notice %></p>
Google Search: <form><input type=text  class="search"><input type=submit value="Submit" onclick="request_google()"></form>
<%= render "site_list" %>
<p>
<%= tag "input", { "type" => "button", "value" => "Edit Frontpage", "onclick"=> "enableEdit()" } %>
</p>